"""Entry point for the TechJam conversational shopping agent.

FROZEN WIRING. Do not edit this file on a feature branch -- it is the one place
all three lanes meet, and it is the only real merge-conflict surface in the
repo. If you need a change here, raise it with the team; one person lands it on
main and everyone rebases.

Per turn:  state update -> search -> rerank -> choose question -> compose reply

  src/extract.py, src/attributes.py, src/lexicons/  -> Lane A
  src/retrieval/                                    -> Lane B
  src/policy/                                       -> Lane C
"""

from __future__ import annotations

import json
import os
import sys
import traceback
from pathlib import Path

from src.attributes import load_attribute_table
from src.contracts import ASK_ATTRIBUTES, ConversationState
from src.policy.message import compose_message
from src.policy.question import choose_question
from src.policy.state import record_question, update
from src.retrieval import Retriever

ARTIFACTS_DIR = os.environ.get("TECHJAM_ARTIFACTS", "artifacts")
DEBUG = bool(os.environ.get("TECHJAM_DEBUG"))
# Ten evaluator turns can consume ten unseen recommendations each. Keep enough
# popularity fallbacks to preserve that contract even if retrieval fails late.
FALLBACK_POOL = 100


def _popular_asins(catalog_path: Path, limit: int) -> list[str]:
    """Highest rating_number products, used to guarantee a full top_k."""
    scored: list[tuple[int, str]] = []
    with catalog_path.open(encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            product = json.loads(line)
            count = product.get("rating_number") or 0
            scored.append((int(count) if isinstance(count, (int, float)) else 0,
                           str(product["parent_asin"])))
    scored.sort(reverse=True)
    return [asin for _, asin in scored[:limit]]


class Agent:
    def __init__(
        self,
        catalog_path: str | Path = "data/catalog.jsonl",
        artifacts_dir: str | Path = ARTIFACTS_DIR,
    ) -> None:
        self.catalog_path = Path(catalog_path)
        self.artifacts_dir = Path(artifacts_dir)
        self.table = load_attribute_table(self.artifacts_dir, self.catalog_path)
        self.retriever = Retriever(self.catalog_path, self.artifacts_dir, self.table)
        self.fallback = _popular_asins(self.catalog_path, FALLBACK_POOL)
        self._states: dict[str, ConversationState] = {}

    def reset(self, session_id: str, user_profile: dict) -> None:
        self._states[session_id] = ConversationState(
            session_id=session_id, user_profile=user_profile or {}
        )

    def respond(self, session_id: str, user_message: str, turn: int, top_k: int) -> dict:
        state = self._states.get(session_id)
        if state is None:
            self.reset(session_id, {})
            state = self._states[session_id]
        try:
            return self._respond(state, user_message, turn, top_k)
        except Exception:
            # The evaluator counts an exception as a miss, so never raise. Fall
            # back to the popularity prior and keep the session alive.
            traceback.print_exc(file=sys.stderr)
            if DEBUG:
                raise
            ranked = self._pad([], top_k, state.shown_recommendations)
            state.shown_recommendations.update(ranked)
            return self._envelope(
                "Let me keep looking — could you tell me a bit more?",
                "other",
                ranked,
            )

    def _respond(self, state: ConversationState, user_message: str, turn: int, top_k: int) -> dict:
        state = update(state, user_message, turn)

        candidates = self.retriever.search(state)
        candidates = self.retriever.rerank(candidates, state)

        # The merged no-repeat rule applies to the whole customer-facing turn,
        # not just the final ASIN slice. Questions must measure the candidates
        # still eligible to be shown, and the prose must explain the product
        # that will actually be returned first.
        eligible_candidates = [
            candidate
            for candidate in candidates
            if candidate.parent_asin not in state.shown_recommendations
        ]

        ask_attribute, extra_topics = choose_question(
            state, eligible_candidates, self.table
        )
        if ask_attribute not in ASK_ATTRIBUTES:
            ask_attribute = "other" if ask_attribute else None
        if ask_attribute:
            record_question(state, turn, ask_attribute, extra_topics)

        message = compose_message(
            state, eligible_candidates, ask_attribute, extra_topics
        )
        state.history.append(("agent", message))

        # A continued scored session proves that every product already shown
        # under this intent was a miss. Re-rank from the customer's latest
        # evidence, then spend all ten slots on the best unseen candidates.
        # state.update clears the exclusions when an intent override arrives,
        # because pre-override recommendations were made for a different need.
        ranked = [
            candidate.parent_asin
            for candidate in eligible_candidates
        ][:top_k]
        ranked = self._pad(ranked, top_k, state.shown_recommendations)
        state.shown_recommendations.update(ranked)
        return self._envelope(message, ask_attribute, ranked)

    def _pad(
        self,
        ranked: list[str],
        top_k: int,
        excluded: set[str] | None = None,
    ) -> list[str]:
        """Fill unused slots from the popularity prior without repeating."""
        if len(ranked) >= top_k:
            return ranked[:top_k]
        seen = set(ranked) | (excluded or set())
        for asin in self.fallback:
            if len(ranked) >= top_k:
                break
            if asin not in seen:
                seen.add(asin)
                ranked.append(asin)
        return ranked

    @staticmethod
    def _envelope(message: str, ask_attribute: str | None, ranked: list[str]) -> dict:
        return {
            "message": message,
            "ask_attribute": ask_attribute,
            "recommendations": [{"parent_asin": asin} for asin in ranked],
            # No model in the scoring path: nothing to report but the shape.
            "usage": {"prompt_tokens": 0, "completion_tokens": 0},
        }
