"""Shared types for the TechJam conversational shopping agent.

FROZEN. Do not edit this file on a feature branch. If you need a change here,
raise it with the team; one person lands it on main and everyone rebases.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

# The nine slots we model. The evaluator's ask_attribute enum also accepts
# "other" and None -- those are policy choices, not slots.
SLOTS = (
    "category", "material", "color", "size", "style",
    "brand", "budget", "feature", "use_case",
)

# Everything the evaluator will accept in ask_attribute.
ASK_ATTRIBUTES = frozenset(SLOTS) | {"other"}


@dataclass
class SlotValue:
    """One thing we believe about what the customer wants."""

    value: str             # normalized: "cotton", "waterproof", "travel"
    confidence: float      # 0.0 - 1.0
    turn: int              # turn it was learned on
    polarity: bool = True  # False for negation: "not leather"


@dataclass
class ConversationState:
    """Everything we know about one session, rebuilt turn by turn."""

    session_id: str
    user_profile: dict
    turn: int = 0
    slots: dict[str, list[SlotValue]] = field(default_factory=dict)
    unanswerable: set[str] = field(default_factory=set)  # boundary: no preference
    asked: list[str] = field(default_factory=list)       # attributes already asked
    last_asked: Optional[str] = None                     # what we asked last turn
    history: list[tuple[str, str]] = field(default_factory=list)  # (role, text)
    budget_max: Optional[float] = None

    def active(self, slot: str) -> list[str]:
        """Current positive values for a slot, most recent first."""
        return [s.value for s in reversed(self.slots.get(slot, [])) if s.polarity]

    def excluded(self, slot: str) -> list[str]:
        """Values the customer has ruled out for a slot."""
        return [s.value for s in self.slots.get(slot, []) if not s.polarity]

    def add(self, slot: str, value: SlotValue) -> None:
        self.slots.setdefault(slot, []).append(value)

    def filled(self) -> list[str]:
        """Slots we have at least one live value for."""
        return [slot for slot in SLOTS if self.active(slot)]


@dataclass
class Candidate:
    """One scored product."""

    parent_asin: str
    score: float
    components: dict[str, float] = field(default_factory=dict)  # bm25/dense/slot
    why: str = ""   # one clause explaining the match, surfaced in the reply
